### ISSUE TITLE
USER STORY: Site intro

### ISSUE THREAD

**Issue by renatabiniek** [renatabiniek/hush-daisies#1]
As a **site user** I can **quickly learn what the site is about** so that **I can decide if it offers something I want**.

**Acceptance Criteria**

1. Branding is prominent once the user enters the site
2. Tagline conveying the site character is clearly visible
3. Link to Our Story section is available in the navigation bar to take the user to the relevant section
4. General idea of the site offer and site owner is presented on the main page

**Tasks**

- [x] Add hero image and the site slogan that will illustrate the purpose of the site to index.html
- [x] Add our studio section, selling points, custom orders section 
- [x] Add Shop now button that links to the shop page
- [x] Add favicon
- [x] Add CSS
- [x] Test the functionality
