### ISSUE TITLE
USER STORY: Workshop favourites

### ISSUE THREAD

**Issue by renatabiniek** [renatabiniek/hush-daisies#10]
As a **registered site user** I can **access my profile page** so that **I can view and edit my list of saved workshops**.

**Acceptance Criteria**
1. Workshop section is displayed on the user's profile page 
2. If there are no items saved to favourites yet, a message is displayed
3. If user had saved a workshop, workshop details are displayed, with the image, name, date and location
4. The name links to the workshop details page for the particular workshop
5. A bookmark icon is displayed next to each item, that can be used to quickly remove the item from favourites
6. Clicking the icon removes the workshop from their profile and a message is displayed

**Tasks**

- [x] Update workshop_details view with the favourites in workshops app
- [x] Update profile html template to display list of workshops
- [x] Add icons to remove each workshop from profile page
- [x] Add link to the workshop name 
- [x] Add CSS
- [x] Test
