### ISSUE TITLE
USER STORY:  Editing products

### ISSUE THREAD

**Issue by renatabiniek** [renatabiniek/hush-daisies#13]
As a **site admin** I can **edit a product** so that **I can keep the products information up-to-date**.

**Acceptance Criteria**

1. Admin can see an Edit link on the products in the shop (products page and product details page)
2. When Edit link is clicked it takes the admin to edit product page
3. Edit product page displays form with current product details
4. Admin can edit the form and submit the changes
5. Admin is redirected to the product detail page of the edited product 
6. Product shows in the store with updated details

**Tasks**

- [x] Create edit_product.html template
- [x] Create the view and url
- [x] Add url to product on products page and product details page
- [x] Update the view to handle posting the form
- [x] Test
