### ISSUE TITLE
USER STORY: Deleting products

### ISSUE THREAD

**Issue by renatabiniek** [renatabiniek/hush-daisies#14]
As a **site admin** I can **delete a product** so that **I can remove items that are no longer for sale**.

**Acceptance Criteria**

1. Admin can see an Delete link on the products in the shop (products page and product details page)
2. When Delete link is clicked a warning modal is displayed wit Cancel and Delete buttons
3. Once Delete is clicked, product is deleted
4. Deleted product cannot be found in the store 

**Tasks**

- [x] Create the view and url
- [x] Create delete product modal
- [x] Add url to product on products page and product details page
- [x] Test
