### ISSUE TITLE
USER STORY:  Comment approval

### ISSUE THREAD

**Issue by renatabiniek** [renatabiniek/hush-daisies#15]
As a **site admin** I can **approve or block comments** so that **only appropriate comments are displayed**.

**Acceptance Criteria**

1. Once submitted, a new testimonial needs to be approved by the superuser in the admin panel
2. Once approved, it's added to the testimonial section
3. If not approved, comment is not showing on the workshop details page

**Tasks**

- [x] Register WorkshopTestimonial model in admin.py so that comments accessible in the admin panel
- [x] Use the boolean field of the model to approve / not approve comments (django functionality)
- [x] Update workshop_details view to filter and show only comments that are approved
- [x] Test
