### ISSUE TITLE
USER STORY: Product list

### ISSUE THREAD

**Issue by renatabiniek** [renatabiniek/hush-daisies#19]
As a **shopper** I can view **a list of products** so that I **can select some to purchase**.

**Acceptance Criteria**

1. All products are listed as cards on the Shop page
2. Overview of the product (name, category, image, price) is visible
3. Only active products are visible
4. Row of items are visually separated

**Tasks**

- [x] Create products app 
- [x] Add app to installed apps in settings.py
- [x] Create products and category models
- [x] Create template, views and url
- [x] Add link to the shop page to the main navbar and Shop Now button
- [x] Add horizontal line between row of items for different screen sizes
- [x] Add filter to show products depending on the user status (all to superadmin, available only to others)
- [x] Test the functionality
