### ISSUE TITLE
USER STORY: Site navigation

### ISSUE THREAD

**Issue by renatabiniek** [renatabiniek/hush-daisies#2]
As a **site user** I can **easily navigate the site** so that **I can find the page I want to go to**.

**Acceptance Criteria**

1. Header with navigation bar is at the top of the page and visible on all pages
2. Logo is prominent and links to the home page
3. Links to important sections and pages are contained in the navbar
4. Footer with social accounts, and other relevant info is visible at the bottom of all pages

**Tasks**

- [x] Create base.html with navigation bar and footer that will be extended in other templates
- [x] Add logo that links to homepage
- [x] Add links to shop, workshops, our studio, contact us and shopping bag 
- [x] Adjust design to be responsive
- [x] Test the functionality
