### ISSUE TITLE
USER STORY: Product details

### ISSUE THREAD

**Issue by renatabiniek** [renatabiniek/hush-daisies#20]
As a **shopper** I can **click a product on the list** so that **I can view further information about the item before purchasing**.

**Acceptance criteria**

1. Clicking the individual product image on the main product list opens a new page with product details
2. There's a link allowing the user to return to the full list of products
3. The details include all necessary information (Image, category, price, description)
4. There's option to select quantity and add to shopping bag button (skeleton form to be expanded with later user stories)

**Tasks**

- [x] Create a view
- [x] Create html template
- [x] Set up urls
- [x] Style the page with CSS
- [x] Add Back to all products link
- [x] Add quantity selector field
- [x] Add Add to shopping bag button
- [x] Add link to product detail to product card in products.html
- [x] Test functionality
