### ISSUE TITLE
USER STORY: Product categories view

### ISSUE THREAD

**Issue by renatabiniek** [renatabiniek/hush-daisies#21]
As a **shopper** I can **easily identify different product categories** so that **I can narrow down my search for relevant products**.

**Acceptance Criteria**

1. Category options are visible on the product list page
2. When category selected, only items linked to the category are displayed.
3. There's a back to all link on the filtered results page

**Tasks**

- [x] Add category option to the top of the products page
- [x] Set up filtering functionality in the show all products view
- [x] Update links on product and product details pages
- [x] Test the functionality
