### ISSUE TITLE
USER STORY: Product sorting

### ISSUE THREAD

**Issue by renatabiniek** [renatabiniek/hush-daisies#22]
As a **shopper** I can **sort the list of products** so that **I can easily identify find the most relevant products for me**.

**Acceptance criteria**

1. There's a selector box with sorting options visible on the product list page
2. Sorting options by name and price, as well as reset sorting option, are available
3. Once option selected, products are sorted as per the sorting option

**Tasks**

- [x] Create the sorting selector box on the product list page
- [x] Add value and current sorting status to each option that will be used in the view to check for sorting
- [x] Update show_all_products view with the sorting functionality
- [x] Add jquery script to change current URL based on the sorting request and return the expected view
- [x] Test the functionality
