### ISSUE TITLE
USER STORY: Product search

### ISSUE THREAD

**Issue by renatabiniek** [renatabiniek/hush-daisies#23]
As a **shopper** I can **search through the list of products by name or description** so that **I can easily find the most relevant products for me**.

**Acceptance Criteria**

1.  There's a search box at the top of the product list page
2.  The user can type a search term in the box
3.  The search runs on product name or description
4.  Relevant results are displayed
5.  The search results are case insensitive
 
**Tasks**

- [x] Create search form on the products page
- [x] Add CSS if needed
- [x] Update show_all_products view using Q
- [x] Test functionality
