### ISSUE TITLE
USER STORY: Search results

### ISSUE THREAD

**Issue by renatabiniek** [renatabiniek/hush-daisies#24]
As a **shopper** I can **see what I’ve searched for and the number of results** so that **I can quickly see whether the products I'm looking for are available**.

**Acceptance Criteria**

1. Number of results is shown on the product / category view pages
2.  Search term used is displayed next to the search results count (if search was performed) 
3.  The name of the category selected is shown next to the search result count (if category clicked)
4.  "All products" are shown if no search and no category was selected 
 
**Tasks**

- [x] Add a new section to hold the search results to product page 
- [x] Add the variable length counting the number of products returned
- [x] Add scenarios for search term, category, all products
- [x] Test functionality
