### ISSUE TITLE
USER STORY: Adding products to shopping bag

### ISSUE THREAD

**Issue by renatabiniek** [renatabiniek/hush-daisies#25]
As a **shopper** I can **add products to my shopping bag** so that **I can store the items until I'm ready to purchase**.

**Acceptance Criteria**

1. Add to basket button is visible on the product detail page 
2. User can click the button to add an item to the basket
3. If item already in the basket, Add to basket button increments its quantity
4. Total in the navbar updates accordingly

**Tasks**

- [x] Create basket app
- [x] Add app to installed apps in settings.py
- [x] Create template, views and url
- [x] Include the basket urls in the project urls file
- [x] Add link to view basket in base.html
- [x] Create context processor
- [x] Update the add to basket form in product_detail.html
- [x] Add delivery treshold 
- [x] Test the functionality
