### ISSUE TITLE
USER STORY: Adjusting shopping bag

### ISSUE THREAD

**Issue by renatabiniek** [renatabiniek/hush-daisies#26]
As a **shopper** I can **adjust quantity of each item in my shopping bag** so that **I can make changes before checkout**.

**Acceptance Criteria**

1. Quantity selector is visible in the basket
2. With + button, the user can increase the quantity of an item in the basket, and decrease it with - button
3. With the Update link, the qty gets updated
4. The user can remove any item by clicking the bin icon, or entering 0 and clicking Update
5. The total in the header and order summary update accordingly
6. The subtotal for each item in the basket updates accordingly

**Tasks**

- [x] Add qty selector to basket.html
- [x] Add Update link to submit new qty
- [x] Create views to handle updating qty and removing items from the basket
- [x] Add urls
- [x] Add action url to basket form
- [x] Add Javascript to handle adjust and remove actions
- [x] Create templatetags and bagtools
- [x] Test the functionality
