### ISSUE TITLE
USER STORY: Viewing shopping bag

### ISSUE THREAD

**Issue by renatabiniek** [renatabiniek/hush-daisies#27]
As a **shopper** I can **view my shopping bag** so that I **can check view the products and total cost of the order before checkout**.

**Acceptance Criteria**

1. User can click on the basket icon and open the basket page
2. If there are no items in the basket,  message and Add something button are displayed
3. If there are items in the basket, relevant details are displayed (incl. image, product name, price, quantity, subtotal and delete icon
4. Summary of the order, with the delivery cost and grand total is visible
5. Remaining spend needed for free delivery is calculated and displayed 

**Tasks**

- [x] Update basket template
- [x] Add CSS
- [x] Set up message for empty basket
- [x] Add free delivery treshold details to settings.py and contexts.py to calculate delivery & remaining spend needed to free delivery
- [x] Set up message for free delivery spend required
- [x] Update the basket icon link in the header
- [x] Test the functionality
