### ISSUE TITLE
USER STORY: Guest orders

### ISSUE THREAD

**Issue by renatabiniek** [renatabiniek/hush-daisies#28]
As a **shopper** I can **place an order as a guest** so that **I can still use the site without having to create an account**.

**Acceptance Criteria**

1. User who is not logged in can browse, add to basket and checkout
2. Prompt to login or create a new account is shown  on the checkout page

**Tasks**

- [x] Ensure all stages for ordering (product list, product detail, add to basket, view to basket, checkout) are accessible for anonymous users
- [x] Check if user is logged in at the checkout form page
- [x] Add message with links to create an account or log in
- [x] Test functionality
