### ISSUE TITLE
USER STORY: Checkout and payment

### ISSUE THREAD

**Issue by renatabiniek** [renatabiniek/hush-daisies#29]
As a **shopper** I **can easily enter my payment details** so that **I can checkout without problems**.

**Acceptance Criteria**

1.  The shopper can click Secure Checkout button on the basket page and see a checkout form 
2.  Form is displayed for the user to enter delivery details 
3.  Separate section is displayed for the user to enter payment details.

**Tasks**

- [x] Create checkout app and add it to installed apps
- [x] Create Order model (order details) and OrderLineItem (individial order line)
- [x] Create model methods: generate order number and save, update total
- [x] Run migrations
- [x] Add models to the admin
- [x] Create signals.py and add functions to listen for new items being added
- [x] Create checkout form in forms.py
- [x] Create checkout view and add url to urls.py
- [x] Create form template and render the form 
- [x] Add url to the secure checkout button in the basket template
- [x] Add Stripe payment elements to render the payment details box
- [x] Add CSS
- [x] Test functionality
