### ISSUE TITLE
USER STORY: Notifications displayed to the user

### ISSUE THREAD

**Issue by renatabiniek** [renatabiniek/hush-daisies#3]
As a **site user** I can **see notifications about changes I have made** so that **I have a clear understanding of the status of the action**.

**Acceptance Criteria**

1. A relevant message displays upon action performed by site user when adding, adjusting or removing items from the basket
2. An error message appears on the products page if no search term entered in the search box
3. Message can be closed with "x" button (doesn't auto-dismiss) 

**Tasks**

- [x] Create bootstrap toasts (success, error, info, warning) in html files
- [x] update message container in base html with django message levels
- [x] update the views for messages for adding, adjusting basket, removing from basket 
- [x] add Bootstrap JavaScript to base.html postload js section to show the toast on any page
- [x] update settings.py to store the messages in session
- [x] Add CSS
- [x] Test functionality
