### ISSUE TITLE
USER STORY: Workshop list

### ISSUE THREAD

**Issue by renatabiniek** [renatabiniek/hush-daisies#31]
As a **site user** I can **view list of upcoming workshop organised by the store owner** so that **I can decide if they are of interest to me.**

**Acceptance Criteria**

1. User can access list of upcoming workshops from the Workshop link in navbar or Our Studio section on home page
2. The page displays welcome message from the store owners
3. List of workshop is displayed, with image, name, location, level and fee
4. Underneath a Save you spot button is visible 
5. Once clicked, the user can register their interest by filling out a contact form
6. For superusers, Edit and Delete links are displayed to manage workshops in the frontend
7. Sorting box is available for the user to sort the workshop list
8. If no workshops are available, message is displayed

**Tasks**

- [x] Create Workshops app, add to installed apps- 
- [x] Create Workshop and Level models, make migrations
- [x] Create view and url, add url to project urls
- [x] Create workshops.html template
- [x] Add url to template to the navbar and index (our studio section)
- [x] Create admin class for Workshop and Level models in admin.py 
- [x] Register Workshop class in admin 
- [x] Add sorting functionality and box
- [x] Test
