### ISSUE TITLE
USER STORY: Workshop details

### ISSUE THREAD

**Issue by renatabiniek** [renatabiniek/hush-daisies#32]
As a **site user** I can **find the date, description, cost and reviews for each workshop** so that **I can make an informed decision about attending**.

**Acceptance Criteria**

1. Clicking the individual workshop image or title on the main workshop list opens a new page with details
2. The details include all necessary information (Image, level, location, price, description)
3. There's a link allowing the user to return to the full list of workshops
4. There is a button allowing the user to contact the store owners to save their spot in the workshop

**Tasks**

- [x] Create workshop details html template
- [x] Create view and url
- [x] Style the page with CSS
- [x]  Add Back to all workshops link
- [x]  Add link to workshop detail to workshop card in workshops.html
- [x] Test functionality
