### ISSUE TITLE
USER STORY: Saving workshops to favourites

### ISSUE THREAD

**Issue by renatabiniek** [renatabiniek/hush-daisies#33]
As a **registered site user** I can **save workshops I'm interested in in my user profile** so that **I can come back to them later**.

**Acceptance Criteria**

1. Logged in user can see a bookmark icon and save to favourites button on workshop details card
2. Once clicked, the workshop is saved to favourites_list of the user
3. Button text changes to Remove from favourites
4. Message is displayed confirming the action
5. For guests users, Sign in to save to favourites link is displayed
6. Once clicked, user is take to the sign in page
 
**Tasks**

- [x] Create WorkshopFavourites model and make migrations
- [x] Create workshop_favourites view and url in profile app
- [x] Add Add to Favourites button to workshop details html
- [x] Update workshop details html to display the button to logged in users only
- [x] Add link to the Sign in page to workshop details html
- [x] Add CSS
- [x] Test
