### ISSUE TITLE
USER STORY: Adding workshop review

### ISSUE THREAD

**Issue by renatabiniek** [renatabiniek/hush-daisies#34]
As a **registered site user** I can **add my review of a workshop I attended** so that I **can share my opinion with the business and other users**.

**Acceptance Criteria**

1. Number of testimonials is displayed on workshop details page
2. Section with testimonials is displayed underneath the workshop details section
3. Individual testimonials, including reviewer name and date are shown with most recent at the top
4. If there's no testimonials, a message is displayed
5. If user is logged in, a comment box is displayed with a button to add a new testimonial
6. If user isn't logged in, there's a message prompting them to do so to post testimonials

**Tasks**

- [x] Create Comment model in the Workshop models.py
- [x] Make and run migrations
- [x] Register in admin
- [x] Add testimonial counter to workshop detail page
- [x] Add testimonials section on the workshop detail page
- [x] Add CSS
- [x] Create testimonials form
- [x] Update views to display comments and comment form
- [x] Update views to handle form posting
- [x] Test
