### ISSUE TITLE
USER STORY: Workshop review management

### ISSUE THREAD

**Issue by renatabiniek** [renatabiniek/hush-daisies#35]
As a **registered site user** I can **edit and remove my review of a workshop I attended** so that **I can update or remove information**.

**Acceptance Criteria**

1. Edit and Delete link show up by a comment a logged in user had posted
2. When Edit link is clicked, the link opens the workshop testimonial form with details pre-populated and a button to update it
3. When updates are submitted, a message is displayed and the testimonial is sent to admin panel for approval
4. Once approved, it appears in the testimonial section
5. When Delete link is clicked, a modal shows up with Delete and Cancel buttons 
6. Cancel button takes the user back to the workshop details page, Delete button deletes the testimonial
7. Once deleted, a message is displayed and the testimonial disappears from the testimonials section
8. User cannot edit or delete testimonials posted by another user

**Tasks**

- [x] Add edit and delete links to workshop_details.html when the reviewer is logged in
- [x] Create the edit testimonial page
- [x] Create the delete modal
- [x] Add CSS
- [x] Create the view and url
- [x] Test
