### ISSUE TITLE
USER STORY: Newsletter signup

### ISSUE THREAD

**Issue by renatabiniek** [renatabiniek/hush-daisies#36]
As a **site user** I can **sign up for a newsletter** so that **I can receive news and promo offers from the store owner**.

**Acceptance Criteria**

1. Newsletter sign up form is displayed in the footer on each page 
2. The form includes input field for email address and a sign up button
3. Once form is submitted, the email address is added to the mailing list on Mailchimp dashboard

**Tasks**

- [x] Create newsletter sign up form on Mailchimp
- [x] Add the form to the footer in base.html
- [x] Adjust CSS to match the site theme
- [x] Test the sign up process
