### ISSUE TITLE
USER STORY: SEO keywords

### ISSUE THREAD

**Issue by renatabiniek** [renatabiniek/hush-daisies#38]
As **the site owner** I have **relevant SEO keywords implemented on my site and site's metadata** so that **the site ranks higher in search results for these keywords and generates more traffic**.

**Acceptance Criteria**

1. Relevant keywords are organically included in the site content
2. The head of the base.html has meta block with relevant keywords 
3. Image alt tags contain keywords

**Tasks** 

- [x] Conduct keyword research to determine relevant keywords for the site and users
- [x] Review and update site content 
- [x] Update the meta element in the head of base.html with description and keywords
