### ISSUE TITLE
USER STORY:  Responsive site

### ISSUE THREAD

**Issue by renatabiniek** [renatabiniek/hush-daisies#4]
As a **site user** I can **access the website on both mobile and desktop** so that **I can view the content anywhere**.

**Acceptance Criteria**

1. All pages look good on all screen sizes
2. Navigation and footbar are present, all important content is visible
3. Images are presented in full and no parts are cut off
4. All flows can be completed with all info and all buttons visible
5. Text size and padding correlates to the screen size

**Tasks**

- [x] review all pages and ensure they look good on all screen sizes
- [x] review flows (order, checkout, product managements, workshop management, profile view, commenting, contact) and ensure they can be executed comfortably and correctly on all screen sizes
- [x] adjust CSS
- [x] write media queries where necessary
