### ISSUE TITLE
USER STORY:  Social accounts

### ISSUE THREAD

**Issue by renatabiniek** [renatabiniek/hush-daisies#40]
As a **site user** I can **find Hush Daisies' social accounts** so that **I can stay up to date with their news**.

**Acceptance Criteria**

1. Icons with links to social media accounts are visible in the footer
2. Each link opens in new tab
3. Links work correctly

**Tasks**

- [x] Add social links to Facebook, Instagram and Twitter to footer
- [x] Ensure the links open in new tab
- [x] Test the links
