### ISSUE TITLE
USER STORY: Contacting the store

### ISSUE THREAD

**Issue by renatabiniek** [renatabiniek/hush-daisies#41]
As a **site user** I can **contact the business** so that **I can ask a question or submit a special request**.

**Acceptance Criteria**

1. Contact links are available on the home page in the banner, Our Studio and Custom Orders sections
2. On workshop page and workshop details page the form can be accessed via the Save your spot buttons
3. Once clicked a contact form opens for the user to fill out
4. The form includes request type drop down where the user can specify the reason for contacting the store owner: custom order quote, general question or booking a spot at a workshop 
5. The form includes: name, email, phone number, body fields and URL field for any web reference
6. There is a submit button that when clicked submits the form and query to admin panel
7. A success or error message is displayed upon submission
8. Back Home button allows the user to go back to the home page without submitting the form

**Tasks**

- [x] Create Queries app, add to installed apps 
- [x] Create CustomRequest model, make migrations
- [x] Create view and url, add url to project urls
- [x] Add url to the get in touch banner, custom orders contact button on the index page, workshop and workshop details pages
- [x] Create form for the requests and queries for the user
- [x] Create custom_requests.html template to render form
- [x] Create admin class for CustomRequest model in admin.py and register it
- [x] Add CSS
- [x] Test
