### ISSUE TITLE
USER STORY: Account setup confirmation

### ISSUE THREAD

**Issue by renatabiniek** [renatabiniek/hush-daisies#42]
As a **registered site user** I can **receive a confirmation email after creating an account** so that **I know the registration was successful**.

**Acceptance Criteria**

1. After signing up for a new account, a message is displayed to the new user prompting them to verify their email address
2. Verification email with a link is received at the email address provided by the user
3. When link is clicked, a new page is displayed with a button to verify the email address 
4. Sign in page is displayed once the button is clicked

**Tasks**:

- [x] On new Gmail account, in Accounts and Import settings enable 2-step verification and generate app password 
- [x] Add email host password and user to Heroku config vars
- [x] Update settings.py to handle real emails and emails printed to console in development
- [x] Test
