### ISSUE TITLE
USER STORY: Active page 

### ISSUE THREAD

**Issue by renatabiniek** [renatabiniek/hush-daisies#44]
As a **site user** I can **see in the site menu which page I'm currently on** so that **I know which part of the website I'm in**

**Acceptance Criteria**

1. Relevant menu item is underline when the URL matches the nav item
2. The underline disappears when another menu item is clicked
3.  When first loaded, Home is underlined

**Tasks**

- [x] Add resolver_match to the main nav html to add current class for matching URL
- [x] Add CSS for the current class 
- [x] Test the functionality
