### ISSUE TITLE
USER STORY: Basket preview

### ISSUE THREAD

**Issue by renatabiniek** [renatabiniek/hush-daisies#47]
As a **shopper** I can **see a preview of my basket every time I make a change** so that **I can always see the up-to-date basket contents**.

**Acceptance Criteria**
1. A small preview of the basket is displayed with the confirmation message when user makes changes to the basket content
2. Total number of items is shown at the top in the preview
3. Image, product name and quantity are shown for each item in the basket 
4. Order total and free delivery message are shown at the bottom

**Tasks**

- [x] Add html to show the shopping cart preview for the success toast
- [x] Add CSS as required
- [x] Test the functionality
