### ISSUE TITLE
USER STORY: Making payment

### ISSUE THREAD

**Issue by renatabiniek** [renatabiniek/hush-daisies#48]
As a **shopper** I can **proceed with my payment** so that **I can complete my purchase**.

**Acceptance Criteria**

1. Once payment details are entered on the checkout page user can click Secure Checkout button and submit the details
2. Error message shows up if the card details are incorrect
3. Confirmation status is shown to the user

**Tasks**

- [x] Add a listener on the card element for the change event
- [x] Get basket totals from basket context and add it in checkout view 
- [x] Install Stripe and add to settings 
- [x] Create payment intent in checkout views
- [x] Add listener to payment form submit event
- [x] Create order in the database upon form submission
- [x] Redirect to success page
- [x] Create checkout success page
- [x] Test functionality
