### ISSUE TITLE
USER STORY: Email order confirmation

### ISSUE THREAD

**Issue by renatabiniek** [renatabiniek/hush-daisies#51]
As a **shopper** I can **receive an email confirmation of my order** so that **I can keep it for my records**.

**Acceptance Criteria**

1. Email confirmation is sent to a user who placed an order
2. Email subject includes business name and order number
3. Email body includes order summary: number, totals, order items date, delivery info

**Tasks**

- [x] Create text templates in checkout app: email subject and email body
- [x] Add a private method to send the confirmation email in the webhook handler
- [x] Update payment_intent_succeeded to send the confirmation email
- [x] Update default from email to settings.py
