### ISSUE TITLE
USER STORY: Adding new products (outside of admin panel)

### ISSUE THREAD

**Issue by renatabiniek** [renatabiniek/hush-daisies#52]
As a **site admin** I can **add a product without going in to the admin panel** so that **I can quickly add new items to my store**.

**Acceptance Criteria**

1. When superuser is logged in, option to manage products shows up in their profile menu
2. Form to add products is displayed on a separate page, once superuser clicks Product Management option on the profile icon
3. The form includes product name, image, description, price, category, product availability checkbox
4. Once product form is submitted, the product shows up in the product list in the shop with the correct info as per form
5. Product name is unique

**Tasks**

- [x] Add ProductForm class in forms.py
- [x] Create view and url to add products 
- [x] Create the add product html template
- [x] Add url to Product Management under Profile
- [x] Update the view to handle posting the form
- [x] Test
