### ISSUE TITLE
USER STORY: Terms of use and privacy policy

### ISSUE THREAD

**Issue by renatabiniek** [renatabiniek/hush-daisies#53]
As a **site user** I can **find terms of use and privacy policy** so that **I can be aware of them while using the site**.

**Acceptance Criteria**
1.  Links to the Terms of Use and Privacy Policy are available in the footer on every page
2. Each link leads to the correct policy
3. The link open in a new window

**Tasks**

- [x]  Create Terms of Use
- [x]  Create Privacy Policy
- [x]  Add links to the footer
- [x]  Test
