### ISSUE TITLE
USER STORY: User profile

### ISSUE THREAD

**Issue by renatabiniek** [renatabiniek/hush-daisies#9]
As a **registered site user** I can **access my profile page** so that **I can view my previous orders and keep track of my purchases**.

**Acceptance Criteria**

1. User can log in and access their profile page
2. The page includes delivery details form, order history and list of saved workshops
3. The form can be populated as needed
4. Personal details can be saved during checkout 
5. If personal information had already been saved, the form is pre-populated 
6. There is a button to update profile information
7. Once updated, a success message is displayed 

**Tasks**

- [x] Create Profiles app
- [x] Create UserProfile model 
- [x] Add post_save receiver for UserProfile model so that user profile is created or updated each time user object is saved
- [x] Attach UserProfile model to Order model
- [x] Set up basic URLs, view and template for the profiles app
- [x] Customize allauth forms
- [x] Build user profile form
- [x] Add post handler to profile view that updates the user info
- [x] Add success message and remove basket content from success toast message for the profile page
- [x] Update checkout_success view to save user info in profile form at checkout
- [x] Update webhook_handler to save profile
- [x] Test the registration flow  (space for workshops available, actual list will be added in the future user story #31 )
